### ISSUE TITLE
Mons command does not show an error when an invalid arg is passed

### ISSUE THREAD

**Issue by travisn** [rook/kubectl-rook-ceph#120]
When any invalid argument is passed to the `mons` command, no error is printed. 

```
% bin/kubectl-rook-ceph mons bad-arg
Info: CephCluster namespace: "rook-ceph"
Info: Rook operator namespace: "rook-ceph"
```

I initially discovered this with a typo in the expected command, and it wasn't obvious why nothing happened:
```
% bin/kubectl-rook-ceph mons restore-qourum
Info: CephCluster namespace: "rook-ceph"
Info: Rook operator namespace: "rook-ceph"
```

**Comment by subhamkrai** [comment]
@travisn here we can't through the error, since `mons` itself is a command and also it acts as a parent command for `restore-quorum` command which is not in other the case for others. for example
below it will give an error
```
./bin/kubectl-rook-ceph operator fdsfs
Calls subcommands like `restart`  and `set <key> <value>` to update  rook-ceph-operator-config configmap
```
 since the operator is acting as a parent command only.

Above is my observation,  others can correct me

**Comment by travisn** [comment]
not much to do about this
