### ISSUE TITLE
Extend feature to skip reconcile of any Ceph daemon! 

### ISSUE THREAD

**Issue by vumrao** [rook/kubectl-rook-ceph#166]
This has been already implemented for OSD and MON here - https://github.com/rook/kubectl-rook-ceph/issues/35. We could implement the same for MGR, MDS and RGW, and any other Ceph daemons!

**Comment by travisn** [comment]
@vumrao Do all the ceph daemons need to be put in debug mode where the pod is up, but the daemon is not running? We had only implemented that for mons and OSDs since they are stateful and it allows commands to be run against the backing state while the daemon process is not running.

From the separate discussion, I was thinking we just need the ability to skip reconcile of a daemon, as was implemented for mons and OSDs in https://github.com/rook/rook/pull/10585. I can see the utility of skipping reconcile for any daemon if they are labeled as such.

**Comment by vumrao** [comment]
@travisn Thanks Travis for considering this feature request. Nope except MON and OSD I do not think we need a daemon where the POD is up and the daemon is not running. I think I got confused about the debug mode, I thought that the debug mode is the one where we have this feature `ability to skip reconcile`.  You are right we need help skipping reconcile for any daemon. I am changing the title.

**Comment by travisn** [comment]
Sounds good, would you mind opening this in the [Rook repo](https://github.com/rook/rook/issues) now? Thanks!

**Comment by vumrao** [comment]
Closing this one, it would be tracked in rook/rook#12785.

**Comment by vumrao** [comment]
> Sounds good, would you mind opening this in the [Rook repo](https://github.com/rook/rook/issues) instead? Thanks!

Thank you, Travis. Done!
