### ISSUE TITLE
Add command to put an OSD or Mon pod in debug mode

### ISSUE THREAD

**Issue by travisn** [rook/kubectl-rook-ceph#35]
OSD and Mon pods in some support cases may need to be put in a mode that will allow commands to be run against the OSD or Mon while the daemon is not running. Let's call this "debug" mode. This is not a normal part of a reconcile, so the krew plugin is the right place for the one-time operation that can be tuned according to need. 

When the admin decides to put an OSD or Mon in debug mode, the sequence of events would be:
1. `kubectl rook-ceph create-debug [--osd-id <id> | mon-id <id>] [--image <alternate-image>]`
2. Perform debug operations in the debug osd pod
3. `kubectl rook-ceph remove-debug [--osd-id <id> | mon-id <id>]`

# create-debug
The command to create the debug pod would make the following modifications to the copy of the deployment:
1. Verifies the deployment exists
1. Scales the original deployment down to 0
1. Copies the deployment spec and make modifications (see below)
1. Creates the debug deployment 

The following modifications are made in the debug deployment:
- Add the suffix "-debug" to the deployment name
- Add a label `ceph.rook.io/debug: "true"` to the deployment so it can be easily detected. 
- Modify the command in the main container to be only a placeholder so the admin can connect to the pod and execute ceph tool commands

# remove-debug

When done debugging, the remove-debug command:
1. Deletes the debug pod
1. Scales back up the original daemon deployment

**Comment by parth-gr** [comment]
[Randy Martinez](https://github.com/randymtz) if you can explain your finding here,

Currently, as per the above details for debugging https://github.com/rook/kubectl-rook-ceph/issues/35#issue-1302623104, I created something  https://github.com/rook/kubectl-rook-ceph/pull/36, please have a look

**Comment by randymtz** [comment]
> Scales the original deployment down to 0

This will need rook PR#10585 merged before we can do this cleanly. Otherwise, if the rook operator is restarted, osd deployment spec will reconcile & potentially interrupt in-progress maintenance commands.

> Copies the deployment spec and make modifications (see below)
Creates the debug deployment
The following modifications are made in the debug deployment:
Add the suffix "-debug" to the deployment name

This is part of `oc debug`. Note: downstream version >=4.10 have a new 'startup probe' we need to ignore. If alike flags are not part of `kubectl debug`, we'll need to catch when the env is ODF; which will be beneficial at the beginning where current default for namespace is defined. 

> Add a label ceph.rook.io/debug: "true" to the deployment so it can be easily detected.
Modify the command in the main container to be only a placeholder so the admin can connect to the pod and execute ceph tool commands

Having the label is a good idea. We can reuse this in various ways.

---

odf 4.10 e.g. 
-  oc debug deployment/rook-ceph-osd-$id --preserve-pod=true --keep-init-containers=true --keep-liveness=false --keep-readiness=false --keep-startup=false --quiet=true -o json --one-container=true -c osd -- sleep infinity | oc create -f - 

  - this creates deploy/rook-ceph-osd-$id-debug
  - upon -debug pod deletion, replicas can scale up to 1.
  - anything needing to persist for now can use /var/log/ceph/ bind. 
    - ^ we should add a recovery hostPath volume for isolation.

---

Lastly, we shouldn't limit this to just mon/osd. pods/{mds,mgr,rgw,noobaa,csi-*} could also benefit from `debug` pods when contention, or maint. is suspected.

**Comment by parth-gr** [comment]
> This is part of oc debug. Note: downstream version >=4.10 have a new 'startup probe' we need to ignore. If alike flags are not part of kubectl debug, we'll need to catch when the env is ODF; which will be beneficial at the beginning where current default for namespace is defined.

How about upstream then?

**Comment by parth-gr** [comment]
> Lastly, we shouldn't limit this to just mon/osd. pods/{mds,mgr,rgw,noobaa,csi-*} could also benefit from debug pods when contention, or maint. is suspected.

That need more rook changes, and just making the deployment down in other cases would be right and easy way

**Comment by travisn** [comment]
Also note that the operator will skip reconciling CRs that have the label `do_not_reconcile: true`, so that's another way to disable the operator from specific CRs.

**Comment by parth-gr** [comment]
> Also note that the operator will skip reconciling CRs that have the label `do_not_reconcile: true`, so that's another way to disable the operator from specific CRs.

But  in rook currently, we are just skipping for mon and osd, for other CR's extra needs to be added

**Comment by parth-gr** [comment]
@travisn  few questions/doubts
1) If we use `kubectl debug` the image should be passed mandatory.
2) Can we directly pass the deployment name, much easier as will be a generic/common function for all deployments?
3) Using `kubectl debug` I am not sure we can do this `Modify the command in the main container to be only a placeholder so the admin can connect to the pod and execute ceph tool commands`. But yaa after creating the pod it can be possible.

**Comment by travisn** [comment]
> @travisn few questions/doubts
> 
> 1. If we use `kubectl debug` the image should be passed mandatory.

As discussed, not sure `kubectl debug` will work since we need to scale down the existing pod before creating the new one.

> 2. Can we directly pass the deployment name, much easier as will be a generic/common function for all deployments?

Yes, sounds good to use the deployment name. So it might look like:
```
kubectl rook-ceph create-debug [--name <deployment>] [--image <alternate-image>]
```

**Comment by vumrao** [comment]
Downstream BZ - https://bugzilla.redhat.com/show_bug.cgi?id=2103256
